language: node_js
node_js:
  - 4.2
sudo: false
before_install:
# Diagnostics
  - npm --version
  - npm config set spin false
  - phantomjs --version
script:
  - while npm run attester-packaged ; do echo Retrying... ; done
notifications:
  email:
    - build@ariatemplates.com
