language: node_js
node_js:
  - 0.10
sudo: false
env:
  global:
    - SAUCE_USERNAME=ariatemplates
    - SAUCE_ACCESS_KEY=620e638e-90d2-48e1-b66c-f9505dcb888b
  matrix:
    - USE_SELENIUM=false BROWSER=phantomjs
    - USE_SELENIUM=false BROWSER=firefox
    - USE_SELENIUM=true BROWSER="internet explorer" BROWSER_PLATFORM="Windows 7" BROWSER_VERSION="11.0"
before_install:
# Settings needed for graphic output in Firefox
  - export DISPLAY=:99.0
  - /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16
# This test fails on Travis in Firefox but works locally, TODO investigate that...
  - sed -i "s/ - test.aria.widgets.container.dialog.movable.test5.MovableDialogTestCaseFive/#/" test/attester-nophantom.yml
# No Flash on Travis
  - sed -i "s/ - test.aria.core.io.IOXDRTest/#/" test/attester-nophantom.yml
# Diagnostics
  - npm --version
  - npm config set spin false
  - phantomjs --version
before_script:
  - ( cd node_modules/selenium-java-robot && npm install )
  - chmod 777 ./travis_sauce_connect.sh
  - ./travis_sauce_connect.sh
  - export SELENIUM_SERVER="http://$SAUCE_USERNAME:$SAUCE_ACCESS_KEY@ondemand.saucelabs.com:80/wd/hub"
script:
  - npm run ci
notifications:
  email:
    - build@ariatemplates.com
