language: node_js
node_js:
  - 0.10
before_install:
# Changing the /etc/hosts file is needed for the selenium Firefox driver to work correctly
# (see https://code.google.com/p/selenium/issues/detail?id=3280)
  - (echo "127.0.0.1 localhost" && cat /etc/hosts) > /tmp/hosts && sudo mv /tmp/hosts /etc/hosts
# Settings needed for graphic output in Firefox
  - export DISPLAY=:99.0
  - /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16
# This test fails on Travis in Firefox but works locally, TODO investigate that...
  - sed -i "s/ - test.aria.widgets.container.dialog.movable.test5.MovableDialogTestCaseFive/#/" test/attester-nophantom.yml
# No Flash on Travis
  - sed -i "s/ - test.aria.core.io.IOXDRTest/#/" test/attester-nophantom.yml
# Diagnostics
  - npm --version
  - npm config set spin false
  - phantomjs --version
# Get an experimental version of noder-js:
  - mkdir node_modules && git clone https://github.com/divdavem/noder-js.git -b exposingProperties node_modules/noder-js
  - npm install -g grunt-cli
  - (cd node_modules/noder-js && npm install)
script:
  - npm run ci
notifications:
  email:
    - build@ariatemplates.com
