language: node_js
node_js:
  - 0.8
before_install:
  - npm config set ca ""
  - phantomjs --version
install:
  - npm install -g grunt-cli
  - npm install
  - (cd node_modules/noder-js && npm install)
notifications:
  email:
    - build@ariatemplates.com
