language: node_js
node_js:
  - 6.10.2
sudo: false
cache:
  yarn: true
  directories:
    - node_modules
addons:
  firefox: "50.0"
  apt:
    packages:
    - awesome
before_install:
# Settings needed for graphic output in Firefox
  - export DISPLAY=:99.0
  - /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16
  - /sbin/start-stop-daemon --start --quiet --pidfile /tmp/awesome_99.pid --make-pidfile --background --exec /usr/bin/awesome
  - yarn global add geckodriver@1.4
# Diagnostics
  - yarn --version
  - phantomjs --version
script:
  - yarn ci
notifications:
  email:
    - build@ariatemplates.com
